### ISSUE TITLE
hazardous use of memcpy on overlapping memory

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-ipsec-mb#109]
memcpy is being used with an overlapping copy operation, perhaps memmove() should be used instead.

static analysis with cppcheck throws the following warning:

lib/avx512_t1/zuc_top_avx512.c:759:25: error: Overlapping read/write in memcpy() is undefined behavior [overlappingWriteFunction]
                        memcpy(keyStr32, &keyStr32[16], 64);

**Comment by pablodelara** [comment]
Thanks @ColinIanKing. I will take a look at this!

**Comment by tkanteck** [comment]
61490ba6f65c7e5efa172c2a41bb62c92102ff55 fixes the problem
