### ISSUE TITLE
the performance does not scale with the number of cores

### ISSUE THREAD

**Issue by kojimr** [intel/intel-ipsec-mb#112]
When using intel-ipsec-mb with multiple threads, the performance does not scale with the number of cores. I found that imb_set_errno() is writing to one global variable "imb_errno" from multiple threads, which is causing the store buffer to run out and the CPU to stall.

I am using intel-ipsec-mb from dpdk, each version is DPDK v22.07 and intel-ipsec-mb v1.20.
For more information, please see the following post to the DPDK users@dpdk.org mailing list.

https://mails.dpdk.org/archives/users/2022-October/006742.html

**Comment by tkanteck** [comment]
Thanks. We'll look into it

**Comment by tkanteck** [comment]
Thanks for flagging it. The fix is on its way.

**Comment by pablodelara** [comment]
Following commit also fixes this issue (impacting direct API): https://github.com/intel/intel-ipsec-mb/commit/9f5adaebcc3d6deac1ad0ddd10309c74318d7c40
