### ISSUE TITLE
error when installing on aws ec2

### ISSUE THREAD

**Issue by michaelsizonenko** [intel/intel-ipsec-mb#113]
nasm version: 2.15.05

When running make or make install after a while an error occurs on the same file as in the screenshot, reproduced on pure ubuntu 22 and Debian 11 on EC2, any idea why this might not work? 
No specific settings on the servers, and not on EC2 servers everything works fine

![image](https://user-images.githubusercontent.com/51369289/204616821-21a3243f-5ea4-4e57-bbc6-6d5f35767195.png)

**Comment by tkanteck** [comment]
We have seen this problem in the past when there was not enough RAM in the system. One of the build processes gets killed due to lack of memory - there should be a notification in `dmesg`

**Comment by tkanteck** [comment]
Hello @michaelsizonenko, did you manage to solve the problem? can we close this issue?

**Comment by michaelsizonenko** [comment]
Yes, we can close. I monitored the memory, and in cases where the compilation failed, I was almost out of memory. 
If there is enough memory, then all goes well.
