### ISSUE TITLE
Ubuntu 22.04 fatal error: utils.h

### ISSUE THREAD

**Issue by jimthedj65** [intel/intel-ipsec-mb#123]
Hi All,

I am running a VM in bypass mode for nics and cpu 

NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

linux-headers-5.15.0-72-generic

I cloned the recent repo from here and when I run **make** I get the following error with a missing helper file from main.c 
```main.c:36:10: fatal error: utils.h: No such file or directory```
  ``` 36 | #include "utils.h"```
    ```  |          ^~~~~~~~~```
make -version GNU Make 4.3
gcc Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)
NASM version 2.16.01 compiled on May 24 2023

any help appreciated

**Comment by jimthedj65** [comment]
I noticed this when running to a > log.txt

make[2]: Entering directory '/home/vm/intel-ipsec-mb/test/kat-app'
cc -MMD -D_GNU_SOURCE -DNO_COMPAT_IMB_API_053 -W -Wall -Wextra -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -fno-delete-null-pointer-checks -fwrapv -std=c99 -fno-strict-overflow -fcf-protection=full -DLINUX -O3   -c -o main.o main.c
main.c:36:10: fatal error: utils.h: No such file or directory
   36 | #include "utils.h"
      |          ^~~~~~~~~

**Comment by tkanteck** [comment]
Thanks for reporting the problem.
It looks that library is installed in the system and then makefile of the test application is omitting one `-I` compiler setting. We'll address it shortly.
For the time being, you can try to uninstall the library `sudo make uninstall`  and then use `env LD_LIBRARY_PATH=<lib path>` when executing the binaries.

**Comment by jimthedj65** [comment]
thanks for the quick response, much appreciated.

**Comment by tkanteck** [comment]
The commit above  fixes the problem. Feel free to re-open if there is any problem with the fix.

**Comment by jimthedj65** [comment]
we have installed a number of times and it appears to be satble now thanks
