### ISSUE TITLE
Possible regression: init_mb_mgr_avx() corrupts state on Windows

### ISSUE THREAD

**Issue by dawid-sabat** [intel/intel-ipsec-mb#147]
@tkanteck we see this issue #115  again after we updated our intel-ipsec-mb to v1.5.

Going through the code I see there was a major refactor there. Could you investigate? Looks like a regression.

**Comment by tkanteck** [comment]
thanks - I'll have a look into it

**Comment by tkanteck** [comment]
Many thanks for your help in hunting it down!

It is not exactly the same but similar in nature.  SIMD register not restored on Windows.
- `sha256_ni_block_sse` doesn't preserve xmm7 register and this is used for IPAD/OPAD calculations on platforms with SHANI. This code is executed as part of the self-test.

**Comment by thiagomacieira** [comment]
Do you have a patch?

**Comment by tkanteck** [comment]
The fix is merged now. Thanks!
