### ISSUE TITLE
Query: can intel-ipsec-mb be used on AMD processor directly?

### ISSUE THREAD

**Issue by riveridea** [intel/intel-ipsec-mb#150]
Not an issue, just wondering, as AMD is also x86 architecture, can I run this library on AMD processor based system? Or have you ever validated if it works or not. Thanks!

**Comment by tkanteck** [comment]
No problem, this is the right place to ask questions.

To answer your question: the library is validated on Intel platforms only. However, it is used as x86 crypto provider in popular frameworks (i.e. DPDK or VPP) and no x86 compatibility problems were reported.
