### ISSUE TITLE
Query: Possible performance degradation of v1.5 with DPDK 23.11?

### ISSUE THREAD

**Issue by riveridea** [intel/intel-ipsec-mb#154]
It is observed some 10% of performance degradation when uplifting the ipsec-mb lib to v1.5 from v1.4 with our DPDK 23.11. 
Have anyone seen similar behavior?
Thanks,

**Comment by tkanteck** [comment]
Hello, Nobody reported such problem. What algorithm and on what HW platform do you observe it with? How can it be replicated?

**Comment by riveridea** [comment]
We will collect more information about it. Need some time. Thanks.

**Comment by tkanteck** [comment]
Hello @riveridea , is there any update on this issue?

**Comment by riveridea** [comment]
It looks like that the DPDK 23.11 is using the  IMB_GET_NEXT_BURST in the dequeue_burst of PMD while the previous DPDK uses the IMB_GET_NEXT_JOB. And the test shows the very high time usage of IMB_GET_NEXT_BURST. Wondering if it is DPDK's PMD issue or intel-ipsec-mb lib problem.

**Comment by pablodelara** [comment]
Did you use the crypto-perf app to see this performance drop? Could you share HW and algorithm where you observe it?

**Comment by riveridea** [comment]
No I just used some end-to-end test to collect the profiling data. I will try the crypto-perf to dig more, it may takes some tome. Thanks. Will update you once any new data.

**Comment by riveridea** [comment]
And one thing for sure, the perf drop in my test is related to DPDK 23.11, regardless of intel-ipsec-mb v1.3 or v1.4.

**Comment by riveridea** [comment]
Hi Thanks for you all. I have identified that is my own code issue when dealing with the DPDK 23.11 which uses the different APIs of dequeue_burst for Ipsec-mb v1.2 and v1.2+. So this is not an issue with either DPDK or Intel-ipsec-mb. 
Thanks again. Will close it.
