### ISSUE TITLE
Discussion: mb_mgr_job_api.h fn tables tab_sumbit_cipher etc could lead to crash if app code pass invalid job 

### ISSUE THREAD

**Issue by riveridea** [intel/intel-ipsec-mb#160]
This is not a bug of the lib code, but sometimes if the app code passes the invalid job to the functions like
SUBMIT_JOB_CIPHER
FLUSH_JOB_CIPHER
could lead to crash because the NULL entry can be result of the populated index from JOB and it crashes here
return tab_submit_cipher[idx](state, job);

The invalid job could happen when the race condition happens between control plane and data plane., especially in DPDK applications. 

Before version 1.3, the crash won't be seen with that corner case because the function table was not used.

I am wondering if any better way exists to avoid the crash.

**Comment by riveridea** [comment]
Thanks for explanation.

**Comment by riveridea** [comment]
I am wondering if there is any follow-up for the rework you mentioned here.

**Comment by tkanteck** [comment]
Thanks for checking. Yes, I am working on it. Not ready to go yet.
