### ISSUE TITLE
Possible executable stack in shared library

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-ipsec-mb#18]
When packaging the library for Debian/Ubuntu the lintian checker reports that the shared library stack is executable. The lintian warning is: shlib-with-executable-stack as follows:

"The listed shared library declares the stack as executable.

Executable stack is usually an error as it is only needed if the code contains GCC trampolines or similar constructs which uses code on the stack. One possible source for false positives are object files built from assembler files which don't define a proper .note.GNU-stack section.

To see the permissions on the stack, run readelf -l on the shared library and look for the program header of type GNU_STACK. In the flag column, there should not be an E flag set."

I was wondering if this can be investigated and fixed

**Comment by tkanteck** [comment]
Thanks for reporting the problem. Since C compiler flags disable stack execution so the problem must be related to assembly files. I'll investigate the problem.

**Comment by tkanteck** [comment]
I believe this patch fixes the problem. Feel free to reopen if required.
Thanks!

**Comment by ColinIanKing** [comment]
Thanks, this fixes the issue for me and I've uploaded the fixed packed to Debian/Ubuntu.
