### ISSUE TITLE
A few issues found with static analysis by CoverityScan

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-ipsec-mb#21]
These may be false positives or real issues, but CoverityScan has found some issues:

https://scan4.coverity.com/reports.htm#v30743/p15480

sha_one_block.c:

251                return;
252
   CID 308771 (#1 of 1): Out-of-bounds access (OVERRUN)
overrun-buffer-val: Overrunning buffer pointed to by ld of 32 bytes by passing it to a function which accesses it at byte offset 56.
253        sha_generic_init(ld, sha_type);
254
255        for (idx = 0; (idx + blk_size) <= length; idx += blk_size)
256                sha_generic_one_block(&inp[idx], ld, is_avx, sha_type);

mb_mgr_code.h:

340                state->init_done[min_idx] = 2;
341                state->lens[min_idx] = AES_BLOCK_SIZE;
   CID 308774 (#2 of 2): Wrong size argument (SIZEOF_MISMATCH)
suspicious_sizeof: Passing argument &pb[16] of type uint8_t * and argument 16UL to function memset is suspicious because sizeof (uint8_t) /*1*/ is expected.
342                memset(&pb[AES_BLOCK_SIZE], 0, AES_BLOCK_SIZE);

**Comment by tkanteck** [comment]
Thanks Colin! I have reviewed the results and made one pointer set up correction as the result.
See https://github.com/intel/intel-ipsec-mb/commit/d88c32c596b15560df46e792eb1fd9ca8e121628

**Comment by tkanteck** [comment]
Thanks again and let me close this issue for now
