### ISSUE TITLE
cant build master/0.52 on Ubuntu 18.04

### ISSUE THREAD

**Issue by kreuzerkrieg** [intel/intel-ipsec-mb#31]
latest `NASM/GCC` from official repo of Ubuntu Bionic
running `make` and I get the following

> avx512/gcm_vaes_avx512.asm:5019: error: invalid combination of opcode and operands
> avx512/gcm_vaes_avx512.asm:4374: ... from macro `GCM_FINALIZE_x4' defined here
> avx512/gcm_vaes_avx512.asm:4126: ... from macro `GCM_ENC_DEC_4x128' defined here
> avx512/gcm_vaes_avx512.asm:3744: ... from macro `GHASH_LAST_8x4' defined here
> avx512/gcm_vaes_avx512.asm:222: ... from macro `VCLMUL_STEP2' defined here
> avx512/gcm_vaes_avx512.asm:5019: error: invalid combination of opcode and operands

Any ideas?

**Comment by tkanteck** [comment]
What NASM version do you use?

**Comment by kreuzerkrieg** [comment]
NASM version 2.13.02

**Comment by kreuzerkrieg** [comment]
aggghhrr that minor version (03) difference?

**Comment by tkanteck** [comment]
Yeah. New instructions that we need are not there in version 2.13.02.
Note that NASM 2.14 is already out
Cheers,
Tomasz

**Comment by kreuzerkrieg** [comment]
Thanks!
