### ISSUE TITLE
Decryption when using CIPHER_HASH order does not produce right output

### ISSUE THREAD

**Issue by pablodelara** [intel/intel-ipsec-mb#33]
When flushing a job decrypting before hashing (where hash operation is not completed, but decryption operation is), the buffer is again decrypted, producing an incorrect output.

Currently, the unit tests do not expose this issue, as this combination is not tested (chain_order = CIPHER_HASH, cipher_direction = DECRYPT, hash_alg != NULL_HASH). New tests will be added, testing this and other chained operation combinations.

**Comment by tkanteck** [comment]
The patch fixes the reported issue
