### ISSUE TITLE
Porting build system to CMake

### ISSUE THREAD

**Issue by soroshsabz** [intel/intel-ipsec-mb#34]
ITNOA

Hi,

I think it is very good choice to port build system to popular cross platform build system who call is [CMake](https://cmake.org/), cause to remove platform specific build system and increasing maintainability and usage.

**Comment by tkanteck** [comment]
Hi,
Perhaps CMake is very good tool but I am not familiar with it. Our current build system is certainly far from being perfect but it covers all required platforms & targets.
Feel free to create a patch enabling CMake builds for Linux (gcc) and Windows (Microsoft (R) Visual Studio C compiler) and we'll be happy to pick it up from there.
Thanks,
Tomasz
