### ISSUE TITLE
Found a bunch of spelling mistakes. 

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-ipsec-mb#63]
Found a bunch of spelling mistakes.  Probably should be fixed. I used "codespell" to find these.

./CONTRIBUTING:225: specifiying ==> specifying
./README.md:115: extentions ==> extensions
./README:122: extentions ==> extensions
./ReleaseNotes.txt:363: enqueing ==> enqueuing
./ReleaseNotes.txt:444: refered ==> referred
./ReleaseNotes.txt:542: algorith ==> algorithm
./test/direct_api_test.c:80: occured ==> occurred
./test/direct_api_test.c:360: occured ==> occurred
./test/direct_api_test.c:445: occured ==> occurred
./test/direct_api_test.c:575: occured ==> occurred
./test/direct_api_test.c:618: occured ==> occurred
./test/direct_api_test.c:720: occured ==> occurred
./test/direct_api_test.c:894: occured ==> occurred
./test/direct_api_test.c:1073: occured ==> occurred
./test/win_x64.mak:48: Od ==> Of
./test/ipsec_xvalid.c:747: substracting ==> subtracting
./test/ipsec_xvalid.c:759: Substract ==> Subtract
./test/aes_cbcs_test.c:3099: lenghts ==> lengths
./test/aes_cbcs_test.c:3548: recieved ==> received
./test/misc.asm:34: funtion ==> function
./test/misc.asm:42: funtion ==> function
./test/gcm_ctr_vectors_test.h:62: Authenication ==> Authentication
./lib/intel-ipsec-mb.h:1659: accomodate ==> accommodate
./lib/intel-ipsec-mb.h:1661: accomodate ==> accommodate
./lib/intel-ipsec-mb.h:1819: availabe ==> available
./lib/const.asm:41: dependant ==> dependent
./lib/des_basic.c:49: inital ==> initial
./lib/des_basic.c:60: permuation ==> permutation
./lib/alloc.c:45: algorthmic ==> algorithmic
./lib/alloc.c:147: extenstions ==> extensions
./lib/libipsec-mb.7:72: UE ==> USE, DUE
./lib/libipsec-mb.7:137: UE ==> USE, DUE
./lib/sse/gcm_sse.asm:1815: tahn ==> than
./lib/sse/gcm_sse.asm:1951: seperately ==> separately
./lib/sse/aes_cfb_sse.asm:154: primarly ==> primarily
./lib/sse/aes_cfb_sse.asm:181: primarly ==> primarily
./lib/avx/gcm_avx_gen2.asm:1744: tahn ==> than
./lib/avx/gcm_avx_gen2.asm:1885: seperately ==> separately
./lib/avx/aes_cfb_avx.asm:150: primarly ==> primarily
./lib/avx/aes_cfb_avx.asm:180: primarly ==> primarily
./lib/avx2/gcm_avx_gen4.asm:1196: lenght ==> length
./lib/avx2/gcm_avx_gen4.asm:2815: tahn ==> than
./lib/avx2/zuc_avx2.asm:1124: Brodcast ==> Broadcast
./lib/include/transpose_avx2.asm:233: outputing ==> outputting
./lib/include/os.asm:45: funtion ==> function
./lib/include/os.asm:53: funtion ==> function
./lib/include/constant_lookup.h:33: instrinsic ==> intrinsic
./lib/include/snow3g_common.h:1644: selectes ==> selects
./lib/include/zuc_internal.h:78: swaped ==> swapped
./lib/include/zuc_internal.h:772: varient ==> variant
./lib/include/const.inc:206: multipled ==> multiplied
./lib/avx512/gcm_vaes_avx512.asm:1352: lenghts ==> lengths
./lib/avx512/gcm_vaes_avx512.asm:1509: lenght ==> length
./lib/avx512/gcm_vaes_avx512.asm:3372: intial ==> initial
./lib/avx512/gcm_vaes_avx512.asm:3707: mulitple ==> multiple
./lib/avx512/gcm_vaes_avx512.asm:3942: intermidiate ==> intermediate
./lib/avx512/gcm_avx512.asm:1123: lenght ==> length
./lib/avx512/gcm_avx512.asm:2704: tahn ==> than
./lib/avx512/mb_mgr_des_avx512.asm:111: unsued ==> unused
./lib/avx512/zuc_avx512.asm:877: ouput ==> output
./lib/avx512/chacha20_avx512.asm:582: Brodcast ==> Broadcast
./lib/avx512/des_x16_avx512.asm:936: temprary ==> temporary, temporarily
./lib/avx512/des_x16_avx512.asm:951: temprary ==> temporary, temporarily
./lib/avx512/des_x16_avx512.asm:1034: temprary ==> temporary, temporarily
./lib/avx512/des_x16_avx512.asm:1051: temprary ==> temporary, temporarily
./lib/avx512/sha1_x16_avx512.asm:210: wil ==> will, well
./lib/avx512/sha256_x16_avx512.asm:187: unneccessary ==> unnecessary
./lib/avx512/sha256_x16_avx512.asm:272: wil ==> will, well
./lib/avx512/aes_docsis_enc_vaes_avx512.asm:1467: lenghts ==> lengths
./perf/ipsec_perf.c:878: beginnig ==> beginning
./perf/ipsec_diff_tool.py:126: occurence ==> occurrence
./perf/ipsec_diff_tool.py:237: contaning ==> containing
./perf/ipsec_diff_tool.py:257: comparision ==> comparison
./perf/ipsec_diff_tool.py:272: ommiting ==> omitting
./perf/ipsec_diff_tool.py:280: contaning ==> containing
./perf/ipsec_diff_tool.py:328: calulates ==> calculates
./perf/README:41: contaning ==> containing

**Comment by tkanteck** [comment]
Many thanks Colin!

I think these solve the problem https://github.com/intel/intel-ipsec-mb/commit/b3ff135fba8ed324ff03ee3f062d89089028336b https://github.com/intel/intel-ipsec-mb/commit/719ef40d6fd66b8ad65ea0043193d07a5c237e16 https://github.com/intel/intel-ipsec-mb/commit/65cf71645db89ded7bac9e160315bbc4e9d42074 https://github.com/intel/intel-ipsec-mb/commit/9e1af9c0a4878ae255a777b8a677b57c37a54cc5

**Comment by ColinIanKing** [comment]
Thanks for fixing these
