### ISSUE TITLE
How to compile v0.54 with centos7 intel-icc?

### ISSUE THREAD

**Issue by lh1015** [intel/intel-ipsec-mb#65]
How to compile v0.54 with centos7 intel-icc?

**Comment by tkanteck** [comment]
was it `make -j CC=icc` that here?

**Comment by lh1015** [comment]
Thank you for your replay!
Yes, i make v0.54 use make -j CC=icc,
Previous compilation failed maybe because memory is not enough, 
After i cheate swapfile，compilation was successful.

**Comment by tkanteck** [comment]
Thanks!
