### ISSUE TITLE
FreeBSD compilation broken with SHARED=y

### ISSUE THREAD

**Issue by Martinfx** [intel/intel-ipsec-mb#67]
When compiling with clang , with SHARE=y, the compilation of the test applications fail due to  Undefined symbol "_aligned_malloc"

```
test@ ~/D/i/test> ./ipsec_xvalid_test
ld-elf.so.1: /usr/local/lib/libIPSec_MB.so.0: Undefined symbol "_aligned_malloc"
test@ ~/D/i/test> ./ipsec_MB_testapp 
ld-elf.so.1: /intel-ipsec-mb/test/ipsec_MB_testapp: Undefined symbol "imb_get_errno"
test@ ~/D/i/test>
```

**Comment by pablodelara** [comment]
Hi @Martinfx , I don't see such issue. Can you make sure you are cleaning up any previously installed intel-ipsec-mb.h headers, by running "gmake uninstall"?
Thanks!

**Comment by Martinfx** [comment]
@pablodelara I ran "gmake unistall" but without changes.

**Comment by Martinfx** [comment]
@pablodelara I ran "gmake unistall" but without changes.
