### ISSUE TITLE
RTE_CRYPTO_CIPHER_AES_CBC decrypt fails with pck size less 16 byte (block size)

### ISSUE THREAD

**Issue by barby1138** [intel/intel-ipsec-mb#74]
Hi,

Should I handle subj pck by some other way - else I have 

Thread 1 "dpdk-crypto-app" received signal SIGSEGV, Segmentation fault.
0x00007ffff712b9af in aes_gcm_dec_256_sse () from /usr/lib/libIPSec_MB.so.0

Thanks

**Comment by tkanteck** [comment]
Please note that AES-CBC is a block cipher that normally requires message size to be multiple of 16 bytes.

**Comment by barby1138** [comment]
Oh I see, thanks.

Czesch!!!

**Comment by tkanteck** [comment]
if you can share snippet of code here then it may help narrow down the problem

**Comment by barby1138** [comment]
No the issue is solved - I had to pad the buffer to be multiple of 16 bytes.
But strange that I had problem only with not padded buffers < 16 bytes and only in DECRYPT,
but may be it just reproduced faster.

Thanks.

**Comment by tkanteck** [comment]
Yep, in encrypt direction it would happen as soon as algorithmic code is executed (after 4, 8 or 16 submissions or after flush operation).
Glad to hear it is solved.
Closing the issue then. Cheers
