### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by pablodelara** [intel/intel-ipsec-mb#89]
The default branch will be renamed from "master" to "main" branch, following the industry trend, to use a more inclusive language.
Further details will be posted in the next days.

**Comment by pablodelara** [comment]
The default has been renamed to main. For anyone that had already cloned the repo, follow these steps to migrate your local repo:

# Switch to the "master" branch:
$ git checkout master

# Rename it to "main":
$ git branch -m master main

# Get the latest commits (and branches!) from the remote:
$ git fetch

# Remove the existing tracking connection with "origin/master":
$ git branch --unset-upstream

# Create a new tracking connection with the new "origin/main" branch:
$ git branch -u origin/main

**Comment by tkanteck** [comment]
Alternatively clone the repo from scratch
