### ISSUE TITLE
Latest release 1.1 doesn't compile on FreeBSD 13

### ISSUE THREAD

**Issue by diizzyy** [intel/intel-ipsec-mb#94]
Hi,

Unfortunately it doesn't anymore and just adding the same definitions as for Linux  doesn't seem to work. It would be appreciated if someone could take a look at it.

```
In file included from avx/mb_mgr_avx.c:36:
In file included from ./include/kasumi_internal.h:42:
include/wireless_common.h:35:10: fatal error: 'intrin.h' file not found
#include <intrin.h>
         ^~~~~~~~~~
1 error generated.
```

Best regards,
Daniel

**Comment by pablodelara** [comment]
Hi @diizzyy. Thanks for flagging this. We have a fix for this that we will push today.

**Comment by pablodelara** [comment]
@diizzyy, fix pushed! I will close this issue, but feel free to reopen it if needed.

**Comment by diizzyy** [comment]
Confirmed working, thanks!
